###
## @Author: Hotaru biyuehuya@gmail.com
## @Blog: https://hotaru.icu
## @Date: 2024-05-03 19:13:44
## @LastEditors: Hotaru biyuehuya@gmail.com
## @LastEditTime: 2024-05-04 16:49:18
###

# Kotori Bot - WebUI Api Documentation

@URL = http://localhost:720
@KEY = TOKEN
@USERNAME = 用户名
@PASSWORD = 密码

### 登录

POST {{URL}}/api/accounts/login HTTP/1.1
Content-Type: application/json

{
  "username": "{{USERNAME}}",
  "password": "{{PASSWORD}}"
}

### 退出登录

POST {{URL}}/api/accounts/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{KEY}}

### 获取所有插件配置信息

GET {{URL}}/api/config/plugins HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{KEY}}

### 获取单个插件配置信息

@pluginName = @kotori-bot/kotori-plugin-webui
GET {{URL}}/api/config/plugins/{{pluginName}} HTTP/1.1
Authorization: Bearer {{KEY}}

### 更新单个插件配置信息

@pluginName = @kotori-bot/kotori-plugin-webui
PUT {{URL}}/api/config/plugins/{{pluginName}} HTTP/1.1
Authorization: Bearer {{KEY}}
Content-Type: application/json

{
  "username": "himeno"
}

### 获取所有机器人实例配置信息

GET {{URL}}/api/config/bots HTTP/1.1
Authorization: Bearer {{KEY}}

### 获取单个机器人实例配置信息

@botName = cmd-test
GET {{URL}}/api/config/bots/{{botName}} HTTP/1.1
Authorization: Bearer {{KEY}}

### 更新单个机器人实例配置信息

@botName = cmd-test
PUT {{URL}}/api/config/bots/{{botName}} HTTP/1.1
Authorization: Bearer {{KEY}}
Content-Type: application/json

{
  "master": 24444
}

### 获取全局配置信息
GET {{URL}}/api/config/global HTTP/1.1
Authorization: Bearer {{KEY}}

### 更新全局配置信息
PUT {{URL}}/api/config/global HTTP/1.1
Authorization: Bearer {{KEY}}
Content-Type: application/json

{
  "port": 721,
}

### 获取所有模块信息

GET {{URL}}/api/data/modules HTTP/1.1
Authorization: Bearer {{KEY}}

### 获取单个模块信息

@moduleName = kotori-plugin-adapter-minecraft
GET {{URL}}/api/data/modules/{{moduleName}} HTTP/1.1
Authorization: Bearer {{KEY}}

### 获取所有机器人实例信息

GET {{URL}}/api/data/bots HTTP/1.1
Authorization: Bearer {{KEY}}

### 获取单个机器人实例信息

@botName2 = cmd-test
GET {{URL}}/api/data/bots/{{botName2}} HTTP/1.1
Authorization: Bearer {{KEY}}

### 获取统计数据

GET {{URL}}/api/data/stats HTTP/1.1
Authorization: Bearer {{KEY}}

# Response:

### 获取实时状态

GET {{URL}}/api/data/status HTTP/1.1
Authorization: Bearer {{KEY}}

### WebSocket 连接

### ws://localhost:{{port + 1}}/webui
### WS 端口为 http 端口 + 1


#### 【Server】实时状态（默认每隔 5 秒发送一次）

Response:

{
  "type": "stats",
  "data": {
    "ram": {
      "total": 23.89745330810547,
      "unused": 12.823219299316406,
      "used": 11.074234008789062,
      "rate": 46.34064503029256
    },
    "cpu": {
      "rate": 71.71194182482655,
      "speed": 2592
    }
  }
}

#### 【Server】控制台日志输出

# Response:

{
  "type": "console_output",
  "data": {
    "level": 30,
    "time": 1714895679747,
    "pid": 14880,
    "label": [],
    "msg": "loaded module kotori-plugin-music version: 1.2.1 author: Himeno <biyuehuya@gmail.com>"
  }
}

#### 【Client】远程执行控制台指令
#### 无返回结果，通过控制台日志输出获取执行结果

Request:

{
  "action": "command",
  "command": "/status"
}
